import { RootState } from "../types";

const initialState: RootState = {
  activeTaxonomy: "Land fire incidents",
  dialog: {
    show: false,
    title: "",
    label: "",
  },
  showSidebar: false,
  showProcedures: false,
  sunburstData: [],
  procedures: {
    "EA fire": [
      {
        id: 1,
        action: "Attack engine crew turn-out",
        agent: ["ae_crew"],
        role: [""],
        quantity: 1,
        abbreviation: "a",
        precedence: "None",
      },
      {
        id: 2,
        action: "Second attack engine crew turn-out",
        agent: ["se_crew"],
        role: [""],
        quantity: 1,
        abbreviation: "b",
        precedence: "None",
      },
      {
        id: 3,
        action: "Ladder department turn-out",
        agent: ["lt_crew"],
        role: [""],
        quantity: 1,
        abbreviation: "c",
        precedence: "None",
      },
      {
        id: 4,
        action: "Travel of attack engine crew to 911 address",
        agent: ["ae_crew"],
        role: [""],
        quantity: 1,
        abbreviation: "d",
        precedence: "a",
      },
      {
        id: 5,
        action: "Travel of second engine crew to 911 address",
        agent: ["se_crew"],
        role: [""],
        quantity: 1,
        abbreviation: "e",
        precedence: "b",
      },
      {
        id: 6,
        action: "Travel of ladder tower crew to 911 address",
        agent: ["lt_crew"],
        role: ["driver"],
        quantity: 1,
        abbreviation: "f",
        precedence: "c",
      },
      {
        id: 7,
        action: "Attack engine crew advance 1.75 inch hose to seat of fire",
        agent: ["ae_crew"],
        role: [""],
        quantity: 1,
        abbreviation: "g",
        precedence: "d",
      },
      {
        id: 8,
        action: "Attack engine driver prepare to pump water",
        agent: ["ae_crew"],
        role: [""],
        quantity: 1,
        abbreviation: "h",
        precedence: "g",
      },
      {
        id: 9,
        action: "Attack fire with tank water aboard attack engine",
        agent: ["ae_crew"],
        role: [""],
        quantity: 1,
        abbreviation: "i",
        precedence: "h",
      },
      {
        id: 10,
        action: "Second engine crew member prepare nearest hydrant for hook-up",
        agent: ["se_crew"],
        role: [""],
        quantity: 1,
        abbreviation: "j",
        precedence: "e",
      },
      {
        id: 11,
        action:
          "Second engine drop 5 inch hose between attack engine and nearest hydrant",
        agent: ["se_crew"],
        role: [""],
        quantity: 1,
        abbreviation: "k",
        precedence: "e",
      },
      {
        id: 12,
        action:
          "Second engine hook to hydrant and attack engine and prepare to pump water",
        agent: ["se_crew"],
        role: [""],
        quantity: 1,
        abbreviation: "l",
        precedence: "k",
      },
      {
        id: 13,
        action: "Attack fire with hydrant water",
        agent: ["se_crew"],
        role: [""],
        quantity: 1,
        abbreviation: "m",
        precedence: "l",
      },
      {
        id: 14,
        action: "Set up ladder tower",
        agent: ["lt_crew"],
        role: [""],
        quantity: 1,
        abbreviation: "n",
        precedence: "f",
      },
    ],
    "Mulch/Compost fires": [
      {
        id: 1,
        action: "Operation central receives fire alert",
        agent: ["ae_crew"],
        role: [""],
        quantity: 1,
        abbreviation: "1",
        precedence: "0",
      },
      {
        id: 1,
        action: "Operation central alerts fire department",
        agent: ["ae_crew", "se_crew"],
        role: [""],
        quantity: 1,
        abbreviation: "3",
        precedence: "1",
      },
      {
        id: 1,
        action: "Fire department move to scene",
        agent: ["se_crew"],
        role: [""],
        quantity: 1,
        abbreviation: "4",
        precedence: "2",
      },
    ],
    "Aircraft emergencies": [
      {
        id: 1,
        action: "Operation central receives aircraft indicent alert",
        agent: ["ae_crew"],
        role: [""],
        quantity: 1,
        abbreviation: "1",
        precedence: "0",
      },
      {
        id: 1,
        action: "Operation central gathers technical aircraft information",
        agent: ["ae_crew"],
        role: [""],
        quantity: 1,
        abbreviation: "2",
        precedence: "1",
      },
      {
        id: 1,
        action: "Operation central alerts fire department",
        agent: ["ae_crew", "se_crew"],
        role: [""],
        quantity: 1,
        abbreviation: "3",
        precedence: "1",
      },
      {
        id: 1,
        action: "Fire department move to scene",
        agent: ["se_crew"],
        role: [""],
        quantity: 1,
        abbreviation: "4",
        precedence: "2",
      },
      {
        id: 1,
        action: "Operation central requests additional firefighting resources",
        agent: ["ae_crew", "lt_crew"],
        role: [""],
        quantity: 1,
        abbreviation: "5",
        precedence: "2",
      },
    ],
    "Brush and Wildland fires": [
      {
        id: 1,
        action: "Operation central receives fire alert",
        agent: ["ae_crew"],
        quantity: 1,
        abbreviation: "1",
        precedence: "0",
      },
      {
        id: 1,
        action: "Operation central gathers geographical information",
        agent: ["ae_crew"],
        quantity: 1,
        abbreviation: "2",
        precedence: "1",
      },
      {
        id: 1,
        action: "Operation central alerts fire department",
        agent: ["ae_crew", "se_crew"],
        quantity: 1,
        abbreviation: "3",
        precedence: "1",
      },
      {
        id: 1,
        action: "Fire department move to scene",
        agent: ["se_crew"],
        quantity: 1,
        abbreviation: "4",
        precedence: "2",
      },
      {
        id: 1,
        action:
          "Operation central requests air resources to survey the scope of damage",
        agent: ["ae_crew", "lt_crew"],
        quantity: 1,
        abbreviation: "4",
        precedence: "2",
      },
      {
        id: 1,
        action: "Operation central requests additional firefighting resources",
        agent: ["ae_crew", "lt_crew"],
        quantity: 1,
        abbreviation: "5",
        precedence: "2",
      },
    ],
    "Hamar Scenario": [
      //TODO: Add missing role fields for all procedures
      {
        action: "1st attack engine crew turn-out",
        agent: ["1st Attack Engine Crew"],
        role: [""],
        quantity: 1,
        abbreviation: "a",
        precedence: "None",
        id: 1,
      },
      {
        action: "2nd attack engine crew turn-out",
        agent: ["2nd Attack Engine Crew"],
        role: [""],
        quantity: 1,
        abbreviation: "b",
        precedence: "None",
        id: 1,
      },
      {
        action: "Patrol vehicle turn-out",
        agent: ["Patrol Vehicle"],
        role: [""],
        quantity: 1,
        abbreviation: "c",
        precedence: "None",
        id: 1,
      },
      {
        agent: ["1st Ambulance"],
        action: "1st Ambulance turn-out",
        id: 1,
        role: [""],
        quantity: 1,
        abbreviation: "d",
        precedence: "None",
      },
      {
        action: "2nd Ambulance turn-out",
        agent: ["2nd Ambulance"],
        role: [""],
        quantity: 1,
        abbreviation: "e",
        precedence: "None",
        id: 1,
      },
      {
        action:
          "First arriving fire department scene size up and establish command ",
        agent: ["1st Attack Engine Crew"],
        role: [""],
        quantity: 1,
        abbreviation: "f",
        precedence: "a",
        id: 1,
      },
    ],
  },
  taxonomies: {
    Hamar: [
      {
        agent: "1st Attack Engine Crew",
        id: 1,
        role: [""],
        parent: "None",
      },
      {
        agent: "Ingolf",
        role: ["Fire Officer"],
        parent: "1st Attack Engine Crew",
        parentId: 1,
        id: 2,
      },
      {
        agent: "Lukas",
        role: ["Firetruck Driver"],
        parent: "1st Attack Engine Crew",
        parentId: 1,
        id: 3,
      },
      {
        agent: "Tormod",
        role: ["Firefighter"],
        parent: "1st Attack Engine Crew",
        parentId: 1,
        id: 4,
      },
      {
        agent: "Theodor",
        role: ["Firefighter"],
        parent: "1st Attack Engine Crew",
        parentId: 1,
        id: 5,
      },
      {
        agent: "Mikael",
        role: ["Firefighter"],
        parent: "1st Attack Engine Crew",
        parentId: 1,
        id: 6,
      },
      {
        agent: "2nd Attack Engine Crew",
        id: 7,
        role: [""],
        parent: "None",
      },
      {
        parent: "2nd Attack Engine Crew",
        agent: "Morten",
        role: ["Fire Officer"],
        parentId: 7,
        id: 8,
      },
      {
        agent: "Peter",
        role: ["Firetruck Driver"],
        parent: "2nd Attack Engine Crew",
        parentId: 7,
        id: 8,
      },
      {
        agent: "Jørgen",
        role: ["Firefighter"],
        parent: "2nd Attack Engine Crew",
        parentId: 7,
        id: 8,
      },
      {
        agent: "Roar",
        role: ["Firefighter"],
        parent: "2nd Attack Engine Crew",
        parentId: 7,
        id: 8,
      },
      {
        agent: "Halvard",
        role: ["Firefighter"],
        parent: "2nd Attack Engine Crew",
        parentId: 7,
        id: 8,
      },
      {
        agent: "Patrol Vehicle",
        parent: "None",
        id: 9,
        role: [""],
      },
      {
        agent: "Herman",
        role: ["Patrol Vehicle Driver"],
        parent: "Patrol Vehicle",
        parentId: 9,
        id: 10,
      },
      {
        agent: "Yngve",
        role: ["Police Officer"],
        parent: "Patrol Vehicle",
        parentId: 9,
        id: 10,
      },
      {
        agent: "1st Ambulance",
        parent: "None",
        id: 11,
        role: [""],
      },
      {
        agent: "Rikard",
        role: ["Ambulance Driver"],
        parent: "1st Ambulance",
        parentId: 11,
        id: 12,
      },
      {
        agent: "Sven",
        role: ["Ambulance Assistant"],
        parent: "1st Ambulance",
        parentId: 11,
        id: 12,
      },
      {
        agent: "2nd Ambulance",
        id: 13,
        role: [""],
        parent: "None",
      },
      {
        agent: "Miriam",
        role: ["Ambulance Assistant"],
        parent: "2nd Ambulance",
        parentId: 13,
        id: 14,
      },
      {
        agent: "Kari",
        role: ["Ambulance Driver"],
        parent: "2nd Ambulance",
        parentId: 13,
        id: 14,
      },
    ],
    Cooking: [
      {
        agent: "Chefs",
        parent: "None",
        id: 1,
        role: [""],
      },
      {
        agent: "Eivind Hellstrøm",
        role: ["Cook"],
        parent: "Chefs",
        parentId: 1,
        id: 2,
      },
    ],
    "Land fire incidents": [
      {
        id: 1,
        agent: "ae_crew",
        parent: "None",
        role: [""],
      },
      {
        id: 2,
        parentId: 1,
        agent: "barry",
        parent: "ae_crew",
        role: ["driver"],
      },
      {
        id: 3,
        parentId: 1,
        agent: "john",
        parent: "ae_crew",
        role: [""],
      },
      {
        id: 4,
        parentId: 1,
        agent: "frank",
        parent: "ae_crew",
        role: [""],
      },
      {
        id: 5,
        agent: "se_crew",
        parent: "None",
        role: [""],
      },
      {
        id: 6,
        parentId: 5,
        agent: "jan",
        parent: "se_crew",
        role: [""],
      },
      {
        id: 7,
        parentId: 5,
        agent: "liz",
        parent: "se_crew",
        role: [""],
      },
      {
        id: 7,
        parentId: 5,
        agent: "kathrin",
        parent: "se_crew",
        role: [""],
      },
      {
        id: 9,
        agent: "lt_crew",
        parent: "None",
        role: [""],
      },
      {
        id: 10,
        parentId: 9,
        agent: "xi",
        parent: "lt_crew",
        role: [""],
      },
      {
        id: 11,
        parentId: 9,
        agent: "lin",
        parent: "lt_crew",
        role: [""],
      },
      {
        id: 12,
        parentId: 9,
        agent: "dahn",
        parent: "lt_crew",
        role: [""],
      },
    ],
    "EA fire": [
      {
        id: 1,
        agent: "ae_crew",
        parent: "None",
        role: [""],
      },
      {
        id: 2,
        parentId: 1,
        agent: "barry",
        parent: "ae_crew",
        role: ["driver"],
      },
      {
        id: 3,
        parentId: 1,
        agent: "john",
        parent: "ae_crew",
        role: [""],
      },
      {
        id: 4,
        parentId: 1,
        agent: "frank",
        parent: "ae_crew",
        role: [""],
      },
      {
        id: 5,
        agent: "se_crew",
        parent: "None",
        role: [""],
      },
      {
        id: 6,
        parentId: 5,
        agent: "jan",
        parent: "se_crew",
        role: [""],
      },
      {
        id: 7,
        parentId: 5,
        agent: "liz",
        parent: "se_crew",
        role: [""],
      },
      {
        id: 7,
        parentId: 5,
        agent: "kathrin",
        parent: "se_crew",
        role: [""],
      },
      {
        id: 9,
        agent: "lt_crew",
        parent: "None",
        role: [""],
      },
      {
        id: 10,
        parentId: 9,
        agent: "xi",
        parent: "lt_crew",
        role: [""],
      },
      {
        id: 11,
        parentId: 9,
        agent: "lin",
        parent: "lt_crew",
        role: [""],
      },
      {
        id: 12,
        parentId: 9,
        agent: "dahn",
        parent: "lt_crew",
        role: [""],
      },
    ],
    "Terror incidents": [],
  },
  tableData: {
    type: "procedures",
    key: "EA fire",
    data: [
      {
        id: 1,
        action: "Attack engine crew turn-out",
        agent: ["ae_crew"],
        quantity: 1,
        abbreviation: "a",
        precedence: "None",
      },
      {
        id: 2,
        action: "Second attack engine crew turn-out",
        agent: ["se_crew"],
        quantity: 1,
        abbreviation: "b",
        precedence: "None",
        parentId: 1,
      },
      {
        id: 3,
        action: "Ladder department turn-out",
        agent: ["lt_crew"],
        quantity: 1,
        abbreviation: "c",
        precedence: "None",
      },
      {
        id: 4,
        action: "Travel of attack engine crew to 911 address",
        agent: ["ae_crew"],
        quantity: 1,
        abbreviation: "d",
        precedence: "a",
      },
      {
        id: 5,
        action: "Travel of second engine crew to 911 address",
        agent: ["se_crew"],
        quantity: 1,
        abbreviation: "e",
        precedence: "b",
      },
      {
        id: 6,
        action: "Travel of ladder tower crew to 911 address",
        agent: ["lt_crew"],
        quantity: 1,
        role: ["driver"],
        abbreviation: "f",
        precedence: "c",
      },
      {
        id: 7,
        action: "Attack engine crew advance 1.75 inch hose to seat of fire",
        agent: ["ae_crew"],
        quantity: 1,
        abbreviation: "g",
        precedence: "d",
      },
      {
        id: 8,
        action: "Attack engine driver prepare to pump water",
        agent: ["ae_crew"],
        quantity: 1,
        abbreviation: "h",
        precedence: "g",
      },
      {
        id: 9,
        action: "Attack fire with tank water aboard attack engine",
        agent: ["ae_crew"],
        quantity: 1,
        abbreviation: "i",
        precedence: "h",
      },
      {
        id: 10,
        action: "Second engine crew member prepare nearest hydrant for hook-up",
        agent: ["se_crew"],
        quantity: 1,
        abbreviation: "j",
        precedence: "e",
      },
      {
        id: 11,
        action:
          "Second engine drop 5 inch hose between attack engine and nearest hydrant",
        agent: ["se_crew"],
        quantity: 1,
        abbreviation: "k",
        precedence: "e",
      },
      {
        id: 12,
        action:
          "Second engine hook to hydrant and attack engine and prepare to pump water",
        agent: ["se_crew"],
        quantity: 1,
        abbreviation: "l",
        precedence: "k",
      },
      {
        id: 13,
        action: "Attack fire with hydrant water",
        agent: ["se_crew"],
        quantity: 1,
        abbreviation: "m",
        precedence: "l",
      },
      {
        id: 14,
        action: "Set up ladder tower",
        agent: ["lt_crew"],
        quantity: 1,
        abbreviation: "n",
        precedence: "f",
      },
    ],
  },
};

export default initialState;
