export const procedureColumns = [
  { title: "Action", field: "action" },
  {
    title: "Agents",
    field: "agents",
  },
  {
    title: "Quantity",
    field: "quantity",
  },
  {
    title: "Abbreviation",
    field: "abbreviation",
    lookup: {
      a: "a",
      b: "b",
      c: "c",
      d: "d",
      e: "e",
      f: "f",
      g: "g",
      h: "h",
      i: "i",
      j: "j",
      k: "k",
      l: "l",
      m: "m",
      n: "n",
    },
  },

  {
    title: "Precedence",
    field: "precedence",
    lookup: {
      None: "None",
      a: "a",
      b: "b",
      c: "c",
      d: "d",
      e: "e",
      f: "f",
      g: "g",
      h: "h",
      i: "i",
      j: "j",
      k: "k",
      l: "l",
      m: "m",
      n: "n",
    },
  },
];
export const taxonomyColumns = [
  {
    title: "Agents",
    field: "agents",
  },
  {
    title: "Precedence",
    field: "precedence",
    lookup: {
      None: "None",
      a: "a",
      b: "b",
      c: "c",
      d: "d",
      e: "e",
      f: "f",
      g: "g",
      h: "h",
      i: "i",
      j: "j",
      k: "k",
      l: "l",
      m: "m",
      n: "n",
    },
  },
];
